language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
script:
- npm run lint
- npm run test
branches:
  only:
  - master