nameOverride: "apibuilder-js-generator"
fullnameOverride: "apibuilder-js-generator"

team: foundation

iamRole: arn:aws:iam::479720515435:role/ecsInstanceRole
image:
  repository: flowcommerce/apibuilder-js-generator

resources:
  limits:
    memory: "4Gi"
    cpu: 1
  requests:
    memory: "4Gi"
    cpu: .05

istioIngress:
  enabled: true
  gateways:
    - key: apibuilder-js-generator-flow-io
      tld: flow.io
      dns: true
      hosts:
        - apibuilder-js-generator.flow.io
    - key: apibuilder-js-generator-flow-pub
      tld: flo.pub
      dns: true
      hosts:
        - apibuilder-js-generator.flo.pub

istioService:
  live:
    hosts:
      - apibuilder-js-generator
      - apibuilder-js-generator.flow.io
      - apibuilder-js-generator.flo.pub
    gateways:
      - mesh
      - apibuilder-js-generator-flow-io
      - apibuilder-js-generator-flow-pub
    stages:
      - deployment: live
        weight: 100

deployments:
  live:
    minReplicas: 2
    maxReplicas: 2
    maxUnavailable: 1

rolloutResource:
  enabled: false

canary:
  enabled: false
