nameOverride: ""
fullnameOverride: ""

service:
  port: 7050
  metricsEndpoint:
    enabled: false

iamRole: arn:aws:iam::479720515435:role/ecsInstanceRole
image:
  repository: flowcommerce/apibuilder-js-generator
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: "4Gi"
    cpu: 1
  requests:
    memory: "4Gi"
    cpu: .05

nodeSelector: {}
affinity: {}
tolerations: {}

ingress:
  enabled: true
  gateways:
    - key: apibuilder-js-generator-flow-io
      tld: flow.io
      hosts:
        - apibuilder-js-generator.flow.io
    - key: apibuilder-js-generator-flow-pub
      tld: flo.pub
      hosts:
        - apibuilder-js-generator.flo.pub

services:
  live:
    hosts:
      - apibuilder-js-generator
      - apibuilder-js-generator.flow.io
      - apibuilder-js-generator.flo.pub
    gateways:
      - mesh
      - apibuilder-js-generator-flow-io
      - apibuilder-js-generator-flow-pub
    stages:
      - deployment: live
        weight: 100

deployments:
  live:
    minReplicas: 2
    maxReplicas: 2
    maxUnavailable: 1
    disruptionBudgetEnabled: true
    targetCPUUtilizationPercentage: 80
    version: #from commandline
    strategy: RollingUpdate
