nameOverride: "apibuilder-js-generator"
fullnameOverride: "apibuilder-js-generator"

team: foundation

service:
  port: 7050

image:
  repository: flowcommerce/apibuilder-js-generator

resources:
  limits:
    memory: "2Gi"
    cpu: 1
  requests:
    memory: "2Gi"
    cpu: .05

istio:
  alb: true
  albFlowioTarget: "alb-prod.flow.io"

istioIngress:
  enabled: true
  gateways:
    - key: apibuilder-js-generator-flow-io
      tld: flow.io
      selector: ingressgateway-flow-io
      dns: true
      hosts:
        - apibuilder-js-generator.flow.io

istioService:
  live:
    hosts:
      - apibuilder-js-generator
      - apibuilder-js-generator.flow.io
    gateways:
      - mesh
      - apibuilder-js-generator-flow-io
    stages:
      - deployment: live
        weight: 100

deployments:
  live:
    minReplicas: 2
    maxReplicas: 2
    maxUnavailable: 1
    serviceAccountName: "flow-prod-eks-apicollective-apibuilder-js-generator-sa"
    serviceAccountIamRole: "arn:aws:iam::479720515435:role/flow-prod-eks-apicollective-role"

nodeSelector:
  karpenter/role: workers
  kubernetes.io/arch: amd64
tolerations:
  - key: "role"
    operator: "Equal"
    value: "workers"
    effect: "NoSchedule"

rolloutResource:
  enabled: false

canary:
  enabled: false